module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/$1",
    "^@app/(.*)$": "<rootDir>/app/$1",
    "^@components/(.*)$": "<rootDir>/app/components/$1",
    "^@ui/(.*)$": "<rootDir>/app/components/ui/$1",
    "^@lib/(.*)$": "<rootDir>/app/lib/$1",
    "^@hooks/(.*)$": "<rootDir>/app/hooks/$1",
    "^@contexts/(.*)$": "<rootDir>/app/contexts/$1",
    "^@types/(.*)$": "<rootDir>/app/types/$1",
    "^@utils/(.*)$": "<rootDir>/app/utils/$1",
    "^@styles/(.*)$": "<rootDir>/app/styles/$1",
    "^@public/(.*)$": "<rootDir>/public/$1",
    "^@api/(.*)$": "<rootDir>/app/api/$1",
    "^@models/(.*)$": "<rootDir>/app/models/$1",
    "^@config/(.*)$": "<rootDir>/app/config/$1",
    "^@locale/(.*)$": "<rootDir>/app/locale/$1",
  },
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
  testMatch: ["**/__tests__/**/*.test.ts"],
  collectCoverageFrom: [
    "app/lib/**/*.ts",
    "app/models/**/*.ts",
    "!**/*.d.ts",
    "!**/*.stories.ts",
    "!**/*.test.ts",
  ],
};
