[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image/*"
  to = "/_next/image/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[functions.server]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Configuration du cache
[build.cache]
  paths = [
    "node_modules/.cache",
    ".next/cache",
    "node_modules",
    ".next",
    "public"
  ]

[functions.update-data]
  schedule = "0 0 * * *"
  runtime = "nodejs18"
  timeout = 30

[functions.import-historical]
  runtime = "nodejs18"
  timeout = 30 
