[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "/api"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[build.processing]
  skip_processing = false

[build.cache]
  clear = false

[functions]
  node_bundler = "esbuild"
  included_files = ["public/**"]
  external_node_modules = ["@prisma/client"]

[functions.server]
  included_files = ["public/**/*", ".next/static/**/*"]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

[functions.update-data]
  schedule = "0 0 * * *"
  runtime = "nodejs18.x"
  timeout = 30

[functions.import-historical]
  runtime = "nodejs18.x"
  timeout = 30

[dev]
  framework = "next"
  targetPort = 3000
  port = 8888
