[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["public/**"]

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions.server]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

# Désactivation du cache pour le débogage
[build.processing]
  skip_processing = true

[build.processing.html]
  pretty_urls = true

# Configuration du cache
[build.cache]
  clear = true

[functions.update-data]
  schedule = "0 0 * * *"
  runtime = "nodejs18"
  timeout = 30

[functions.import-historical]
  runtime = "nodejs18"
  timeout = 30 
