[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "/.netlify/functions"
  NEXT_TELEMETRY_DISABLED = "1"

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[build.cache]
  clear = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["public/**"]
  external_node_modules = ["@prisma/client"]

[functions.server]
  included_files = ["public/**/*", ".next/static/**/*"]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

[functions.update-data]
  schedule = "0 0 * * *"
  runtime = "nodejs18.x"
  timeout = 30

[functions.import-historical]
  runtime = "nodejs18.x"
  timeout = 30

[dev]
  framework = "next"
  targetPort = 3000
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/image/*"
  to = "/_next/image/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()" 