/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/contact`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/buy` | `/buy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/checkout` | `/checkout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dazbox` | `/dazbox`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/daznode` | `/daznode`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dazpay` | `/dazpay`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/features` | `/features`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/how-it-works` | `/how-it-works`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/register/[plan]`, params: Router.UnknownInputParams & { plan: string | number; } } | { pathname: `/subscribe/[plan]`, params: Router.UnknownInputParams & { plan: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/contact`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/buy` | `/buy`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/checkout` | `/checkout`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dazbox` | `/dazbox`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/daznode` | `/daznode`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dazpay` | `/dazpay`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/features` | `/features`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/how-it-works` | `/how-it-works`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/register/[plan]`, params: Router.UnknownOutputParams & { plan: string; } } | { pathname: `/subscribe/[plan]`, params: Router.UnknownOutputParams & { plan: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/contact${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/account${`?${string}` | `#${string}` | ''}` | `/account${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/buy${`?${string}` | `#${string}` | ''}` | `/buy${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/checkout${`?${string}` | `#${string}` | ''}` | `/checkout${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dazbox${`?${string}` | `#${string}` | ''}` | `/dazbox${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/daznode${`?${string}` | `#${string}` | ''}` | `/daznode${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dazpay${`?${string}` | `#${string}` | ''}` | `/dazpay${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/features${`?${string}` | `#${string}` | ''}` | `/features${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/how-it-works${`?${string}` | `#${string}` | ''}` | `/how-it-works${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/contact`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/buy` | `/buy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/checkout` | `/checkout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dazbox` | `/dazbox`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/daznode` | `/daznode`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dazpay` | `/dazpay`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/features` | `/features`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/how-it-works` | `/how-it-works`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | `/register/${Router.SingleRoutePart<T>}` | `/subscribe/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/register/[plan]`, params: Router.UnknownInputParams & { plan: string | number; } } | { pathname: `/subscribe/[plan]`, params: Router.UnknownInputParams & { plan: string | number; } };
    }
  }
}
